[profile.default]
src = "src"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
solc-version = "0.8.23"

gas_reports = ["VoteToken", "GovernanceLogic"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
